// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SisEUs.Infrastructure.Repositorios;

#nullable disable

namespace SisEUs.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260126025227_MigracaoMySQL")]
    partial class MigracaoMySQL
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SisEUs.Domain.Checkin.Entidades.Checkin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataHoraCheckIn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataHoraCheckOut")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Latitude")
                        .HasColumnType("double");

                    b.Property<double>("Longitude")
                        .HasColumnType("double");

                    b.Property<int>("PinId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Checkins");
                });

            modelBuilder.Entity("SisEUs.Domain.Checkin.Entidades.CheckinPin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataGeracao")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CheckinPins");
                });

            modelBuilder.Entity("SisEUs.Domain.ContextoDeEvento.Entidades.Apresentacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EventoId")
                        .HasColumnType("int");

                    b.Property<int>("Modalidade")
                        .HasColumnType("int");

                    b.Property<string>("NomeAutor")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeOrientador")
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("EventoId")
                        .HasDatabaseName("IX_Apresentacoes_EventoId");

                    b.ToTable("Eventos", (string)null);
                });

            modelBuilder.Entity("SisEUs.Domain.ContextoDeEvento.Entidades.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AvaliadoresIds")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Avaliadores");

                    b.Property<string>("CodigoUnico")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ParticipantesIds")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Participantes");

                    b.Property<string>("PinCheckin")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoUnico")
                        .IsUnique()
                        .HasDatabaseName("IX_Eventos_CodigoUnico");

                    b.HasIndex("DataInicio")
                        .HasDatabaseName("IX_Eventos_DataInicio");

                    b.ToTable("Sessao", (string)null);
                });

            modelBuilder.Entity("SisEUs.Domain.ContextoDeEvento.Entidades.Presenca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CheckIn")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("CheckInValido")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("CheckOut")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("CheckOutValido")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EventoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CheckIn")
                        .HasDatabaseName("IX_Presencas_CheckIn");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("IX_Presencas_Usuario");

                    b.HasIndex("CheckInValido", "CheckOutValido")
                        .HasDatabaseName("IX_Presencas_Status");

                    b.HasIndex("EventoId", "UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("IX_Presencas_Evento_Usuario");

                    b.HasIndex("UsuarioId", "EventoId")
                        .IsUnique();

                    b.ToTable("Presencas", (string)null);
                });

            modelBuilder.Entity("SisEUs.Domain.ContextoDeUsuario.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EUserType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Matricula")
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserIdentifier")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("EUserType")
                        .HasDatabaseName("IX_Usuarios_Tipo");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("SisEUs.Domain.ContextoDeEvento.Entidades.Apresentacao", b =>
                {
                    b.HasOne("SisEUs.Domain.ContextoDeEvento.Entidades.Evento", "Evento")
                        .WithMany("Apresentacoes")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("SisEUs.Domain.ContextoDeEvento.Entidades.Evento", b =>
                {
                    b.OwnsOne("SisEUs.Domain.ContextoDeEvento.ObjetosDeValor.Localizacao", "Localizacao", b1 =>
                        {
                            b1.Property<int>("EventoId")
                                .HasColumnType("int");

                            b1.Property<string>("Latitude")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("LocalizacaoLatitude");

                            b1.Property<string>("Longitude")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("LocalizacaoLongitude");

                            b1.HasKey("EventoId");

                            b1.ToTable("Sessao");

                            b1.WithOwner()
                                .HasForeignKey("EventoId");
                        });

                    b.OwnsOne("SisEUs.Domain.ContextoDeEvento.ObjetosDeValor.Local", "Local", b1 =>
                        {
                            b1.Property<int>("EventoId")
                                .HasColumnType("int");

                            b1.Property<string>("Bloco")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("LocalBloco");

                            b1.Property<string>("Campus")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("LocalCampus");

                            b1.Property<string>("Departamento")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("LocalDepartamento");

                            b1.Property<string>("Sala")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("LocalSala");

                            b1.HasKey("EventoId");

                            b1.ToTable("Sessao");

                            b1.WithOwner()
                                .HasForeignKey("EventoId");
                        });

                    b.Navigation("Local")
                        .IsRequired();

                    b.Navigation("Localizacao")
                        .IsRequired();
                });

            modelBuilder.Entity("SisEUs.Domain.ContextoDeEvento.Entidades.Presenca", b =>
                {
                    b.OwnsOne("SisEUs.Domain.ContextoDeEvento.ObjetosDeValor.Localizacao", "Localizacao", b1 =>
                        {
                            b1.Property<int>("PresencaId")
                                .HasColumnType("int");

                            b1.Property<string>("Latitude")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("LocalizacaoLatitude");

                            b1.Property<string>("Longitude")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("LocalizacaoLongitude");

                            b1.HasKey("PresencaId");

                            b1.ToTable("Presencas");

                            b1.WithOwner()
                                .HasForeignKey("PresencaId");
                        });

                    b.Navigation("Localizacao")
                        .IsRequired();
                });

            modelBuilder.Entity("SisEUs.Domain.ContextoDeUsuario.Entidades.Usuario", b =>
                {
                    b.OwnsOne("SisEUs.Domain.ContextoDeUsuario.ObjetosDeValor.NomeCompleto", "Nome", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("Nome");

                            b1.Property<string>("Sobrenome")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("Sobrenome");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("Nome")
                        .IsRequired();
                });

            modelBuilder.Entity("SisEUs.Domain.ContextoDeEvento.Entidades.Evento", b =>
                {
                    b.Navigation("Apresentacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
